/**
 * AGENTS.md writer for `ai-memory rules --target agents-md`.
 *
 * AGENTS.md is the cross-tool standard adopted by 60K+ repositories
 * under Linux Foundation Agentic AI Foundation stewardship — natively
 * read by OpenAI Codex, Cursor, Windsurf, Sourcegraph Amp, GitHub Copilot.
 * (Claude Code currently prefers CLAUDE.md but AGENTS.md support is pending.)
 *
 * Semantics are intentionally idempotent and conflict-aware:
 *   - no file                          → create AGENTS.md with header + section
 *   - file present, no managed markers → append our section to the bottom,
 *                                        leaving every hand-written line untouched
 *   - file present, our section found  → replace ONLY between the markers
 *   - byte-identical generated section → no-op (action="already-up-to-date")
 *   - malformed markers (missing/duplicated/inverted) → refuse, return conflict
 *
 * Marker tokens are HTML comments so they render as nothing in any Markdown
 * viewer. The section between them is the only thing this writer ever
 * mutates; everything outside is preserved byte-for-byte.
 */

import { readFile, writeFile } from "node:fs/promises";
import type { ExtractedMemory } from "../types.js";

// ---------- Constants ----------

export const AGENTS_MD_DEFAULT_PATH = "AGENTS.md";

export const MARKER_START = "<!-- ai-memory:managed-section start -->";
export const MARKER_END = "<!-- ai-memory:managed-section end -->";

const FILE_HEADER_EN = `# AGENTS.md

> Instructions for AI coding agents working on this repository.
> Sections wrapped by \`<!-- ai-memory:managed-section ... -->\` are
> auto-generated by \`ai-memory rules --target agents-md\`. Edit memories
> via \`ai-memory list\` / \`extract\` / \`resolve\` rather than this file.
`;

const FILE_HEADER_ZH = `# AGENTS.md

> 本仓库面向 AI 编程助手的统一指令。
> 被 \`<!-- ai-memory:managed-section ... -->\` 包裹的内容由
> \`ai-memory rules --target agents-md\` 自动生成；要修改请用
> \`ai-memory list\` / \`extract\` / \`resolve\`，不要直接编辑该段。
`;

// ---------- Types ----------

export type MergeAction =
  | "created"
  | "updated"
  | "appended"
  | "already-up-to-date"
  | "conflict";

export interface MergeResult {
  action: MergeAction;
  /** Full file content to write. Undefined for conflict / already-up-to-date. */
  nextContent?: string;
  /** Why we refused (populated for `conflict`). */
  reason?: string;
}

export interface WriteAgentsMdOptions {
  language: "zh" | "en";
  /** Output path — defaults to AGENTS.md in the current working directory. */
  outputPath?: string;
}

export interface WriteAgentsMdResult {
  action: MergeAction;
  outputPath: string;
  /** True when we actually wrote bytes to disk. */
  wrote: boolean;
  /** Memory counts by type (for the report). */
  conventions: number;
  decisions: number;
  reason?: string;
}

// ---------- Pure section-content rendering ----------

function escapeForMarkdown(text: string): string {
  // AGENTS.md is plain markdown; we only need to keep the content readable.
  // We do NOT escape `#`, `*`, etc. because the user's content is already
  // markdown-formatted by the extraction prompt. We DO normalise CRLF →
  // LF so re-writes are stable across platforms.
  return text.replace(/\r\n/g, "\n").trim();
}

function renderEntry(m: ExtractedMemory, language: "zh" | "en"): string {
  const lines: string[] = [];
  lines.push(`### ${m.title.trim()}`);
  lines.push("");
  lines.push(escapeForMarkdown(m.content));
  if (m.reasoning) {
    lines.push("");
    lines.push(`${language === "zh" ? "原因" : "Why"}: ${escapeForMarkdown(m.reasoning)}`);
  }
  if (m.alternatives) {
    lines.push("");
    lines.push(
      `${language === "zh" ? "已排除方案" : "Rejected"}: ${escapeForMarkdown(m.alternatives)}`
    );
  }
  return lines.join("\n");
}

/**
 * Pure renderer: returns the section content (incl. start/end markers) that
 * should end up in AGENTS.md. Output is deterministic for the same inputs —
 * we deliberately omit timestamps and counts so re-running the command on an
 * unchanged store produces a byte-identical section (idempotent).
 */
export function buildManagedSection(
  memories: ExtractedMemory[],
  language: "zh" | "en"
): string {
  const conventions = memories.filter((m) => m.type === "convention");
  const decisions = memories.filter((m) => m.type === "decision");

  const lines: string[] = [];
  lines.push(MARKER_START);
  lines.push(
    language === "zh"
      ? "<!-- 自动生成 — 请勿手工编辑。修改请使用 ai-memory list / extract / resolve。 -->"
      : "<!-- AUTO-GENERATED — do not edit by hand. Manage entries via ai-memory list / extract / resolve. -->"
  );
  lines.push("");

  if (conventions.length > 0) {
    lines.push(
      language === "zh"
        ? "## 项目约定（由 AI 对话历史提取）"
        : "## Project conventions (extracted from AI chat history)"
    );
    lines.push("");
    for (const m of conventions) {
      lines.push(renderEntry(m, language));
      lines.push("");
    }
  }

  if (decisions.length > 0) {
    lines.push(
      language === "zh"
        ? "## 技术决策（由 AI 对话历史提取）"
        : "## Technical decisions (extracted from AI chat history)"
    );
    lines.push("");
    for (const m of decisions) {
      lines.push(renderEntry(m, language));
      lines.push("");
    }
  }

  if (conventions.length === 0 && decisions.length === 0) {
    lines.push(
      language === "zh"
        ? "<!-- ai-memory 还没有提取到任何约定或决策。运行 `ai-memory extract` 来生成。 -->"
        : "<!-- ai-memory has not extracted any conventions or decisions yet. Run `ai-memory extract` first. -->"
    );
    lines.push("");
  }

  lines.push(MARKER_END);
  // Single trailing newline so the section sits on its own line group when appended
  return lines.join("\n");
}

// ---------- Pure merge logic ----------

/**
 * Marker tokens are only recognised when they sit at column 0 of their own
 * line (trailing whitespace is tolerated because some editors add it). This
 * deliberately rejects:
 *
 *   1. The literal marker text appearing inside a fenced code block in a
 *      tutorial inside the user's hand-written `AGENTS.md`. Authors usually
 *      indent such examples to nest them under a heading or list item, so
 *      requiring zero leading whitespace lets us safely ignore them.
 *   2. The marker text appearing inline inside a sentence (e.g. a comment in
 *      a paragraph), which would not be on its own line at all.
 *
 * The canonical form ai-memory itself emits is always "marker on its own
 * line, no indentation", so this rule is friendly to anything we wrote and
 * strict about anything that could be a quoted example.
 */
const MARKER_START_LINE_RE_G =
  /^<!-- ai-memory:managed-section start -->[ \t]*$/gm;
const MARKER_END_LINE_RE_G =
  /^<!-- ai-memory:managed-section end -->[ \t]*$/gm;

interface LineMatch {
  /** Byte offset of the FIRST character of the marker line (incl. leading whitespace). */
  lineStart: number;
  /** Byte offset just AFTER the last character of the marker line (excl. its trailing newline). */
  lineEnd: number;
}

function findAllLineMatches(
  source: string,
  re: RegExp
): LineMatch[] {
  const matches: LineMatch[] = [];
  for (const m of source.matchAll(re)) {
    if (m.index === undefined) continue;
    matches.push({ lineStart: m.index, lineEnd: m.index + m[0].length });
  }
  return matches;
}

/**
 * Locate the managed section in `existing`. Returns:
 *   - { kind: "missing" }                          when no markers found
 *   - { kind: "found", startIdx, endIdx }          when exactly one valid pair found
 *   - { kind: "malformed", reason: string }        when markers are corrupted
 *
 * Indices are byte offsets into `existing`. `startIdx` is the line start of
 * the start marker (inclusive); `endIdx` is the byte just past the end marker
 * line (exclusive of any trailing newline). Replacement code slices
 * `[startIdx, endIdx)` so leading indentation on the marker line is part of
 * what gets replaced — the new section is rendered without leading spaces,
 * which matches AGENTS.md convention.
 */
function locateManagedSection(
  existing: string
):
  | { kind: "missing" }
  | { kind: "found"; startIdx: number; endIdx: number }
  | { kind: "malformed"; reason: string } {
  const starts = findAllLineMatches(existing, MARKER_START_LINE_RE_G);
  const ends = findAllLineMatches(existing, MARKER_END_LINE_RE_G);

  if (starts.length === 0 && ends.length === 0) {
    return { kind: "missing" };
  }
  if (starts.length > 1) {
    return {
      kind: "malformed",
      reason: `found ${starts.length} start markers; expected exactly 1`,
    };
  }
  if (ends.length > 1) {
    return {
      kind: "malformed",
      reason: `found ${ends.length} end markers; expected exactly 1`,
    };
  }
  if (starts.length === 0 || ends.length === 0) {
    return {
      kind: "malformed",
      reason: `unbalanced markers (start=${starts.length}, end=${ends.length})`,
    };
  }

  const startMatch = starts[0];
  const endMatch = ends[0];

  if (startMatch.lineStart > endMatch.lineStart) {
    return {
      kind: "malformed",
      reason: "end marker appears before start marker",
    };
  }

  return {
    kind: "found",
    startIdx: startMatch.lineStart,
    endIdx: endMatch.lineEnd,
  };
}

/**
 * Merge `generatedSection` into `existing`. Pure — no IO.
 *
 * Branch summary:
 *   1. existing === null              → action: created
 *   2. existing has no markers        → action: appended
 *   3. existing has matching markers, byte-equal section → already-up-to-date
 *   4. existing has matching markers, different section  → updated
 *   5. existing has malformed markers → conflict
 */
export function mergeAgentsMd(
  existing: string | null,
  generatedSection: string,
  language: "zh" | "en" = "en"
): MergeResult {
  if (existing === null) {
    const header = language === "zh" ? FILE_HEADER_ZH : FILE_HEADER_EN;
    return {
      action: "created",
      nextContent: `${header}\n${generatedSection}\n`,
    };
  }

  const located = locateManagedSection(existing);

  if (located.kind === "malformed") {
    return {
      action: "conflict",
      reason:
        `existing AGENTS.md has malformed ai-memory markers — ${located.reason}. ` +
        `Refusing to write to avoid corrupting the file. ` +
        `Fix the markers manually (or remove them entirely to let ai-memory append a fresh section).`,
    };
  }

  if (located.kind === "missing") {
    // Append. Make sure there's exactly one blank line between user's content
    // and our section so renderers separate them cleanly.
    const trimmed = existing.replace(/\s+$/, "");
    return {
      action: "appended",
      nextContent: `${trimmed}\n\n${generatedSection}\n`,
    };
  }

  // located.kind === "found": replace section between markers (inclusive)
  const before = existing.slice(0, located.startIdx);
  const after = existing.slice(located.endIdx);

  const currentSection = existing.slice(located.startIdx, located.endIdx);
  if (currentSection === generatedSection) {
    return { action: "already-up-to-date" };
  }

  return {
    action: "updated",
    nextContent: `${before}${generatedSection}${after}`,
  };
}

// ---------- Filesystem IO ----------

async function safeReadFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return null;
  }
}

/**
 * Build the section, merge with existing AGENTS.md (if any), and write.
 * Returns a structured report describing what happened.
 */
export async function writeAgentsMd(
  memories: ExtractedMemory[],
  options: WriteAgentsMdOptions
): Promise<WriteAgentsMdResult> {
  const { language } = options;
  const outputPath = options.outputPath ?? AGENTS_MD_DEFAULT_PATH;

  const conventions = memories.filter((m) => m.type === "convention").length;
  const decisions = memories.filter((m) => m.type === "decision").length;

  const section = buildManagedSection(memories, language);
  const existing = await safeReadFile(outputPath);
  const merge = mergeAgentsMd(existing, section, language);

  if (merge.action === "conflict") {
    return {
      action: "conflict",
      outputPath,
      wrote: false,
      conventions,
      decisions,
      reason: merge.reason,
    };
  }

  if (merge.action === "already-up-to-date" || !merge.nextContent) {
    return {
      action: "already-up-to-date",
      outputPath,
      wrote: false,
      conventions,
      decisions,
    };
  }

  // Avoid touching mtime if the next bytes are identical to current bytes
  // (covers the rare case where caller forced a rewrite but content matched).
  if (existing !== null && existing === merge.nextContent) {
    return {
      action: "already-up-to-date",
      outputPath,
      wrote: false,
      conventions,
      decisions,
    };
  }

  await writeFile(outputPath, merge.nextContent, "utf-8");
  return {
    action: merge.action,
    outputPath,
    wrote: true,
    conventions,
    decisions,
  };
}
