/**
 * LongMemEval-50 adapter — pure types shared between loader, runner, and
 * scorer. No filesystem imports here so the unit tests can pull this in
 * without a hot path.
 *
 * Schema mirrors the upstream LongMemEval-S-cleaned JSON file. We keep
 * field names verbatim from the dataset so a reader chasing the
 * upstream README doesn't have to translate.
 *
 * See `docs/cceb-v1.1-and-longmemeval-spike-2026-04-27.md` §4 for the
 * locked selection strategy and scoring rubric.
 */

import type { MemoryType } from "../../src/types.js";

// ---------- Question types LongMemEval ships ----------

/** All non-abstention question types we score. Abstention (`*_abs`) is
 *  deliberately excluded — see spike doc §4.2. */
export type LongMemEvalType =
  | "single-session-user"
  | "single-session-assistant"
  | "single-session-preference"
  | "temporal-reasoning"
  | "knowledge-update"
  | "multi-session";

// ---------- Raw dataset shapes (upstream JSON) ----------

/** One turn inside one session of `haystack_sessions`. */
export interface HaystackTurn {
  role: "user" | "assistant";
  content: string;
  /** Set on turns containing the answer evidence; used by upstream
   *  for turn-level recall metrics, not used by us. */
  has_answer?: boolean;
}

/** One sample from `longmemeval_s_cleaned.json`.
 *
 * `answer` is `string | number` because upstream LongMemEval-S-cleaned has
 * ~6% of samples (32 / 500 in the 2026-04 snapshot) where the answer is a
 * raw count (e.g. `2`, `3`, `5`) for "how many times did X happen"
 * questions. Our loader filters those out — the evidence-preservation
 * rubric is undefined for numeric answers (a key-token list of `["2"]`
 * gets filtered by MIN_TOKEN_LEN and degenerates to "full" via the
 * empty-token fallback, which would silently inflate the headline).
 * See spike doc §4.2 (re-spike outcome 2026-04-27).
 */
export interface LongMemEvalSample {
  question_id: string;
  question_type: string; // upstream may include `_abs` suffix; we filter
  question: string;
  answer: string | number;
  question_date: string;
  haystack_session_ids: string[];
  haystack_dates: string[];
  haystack_sessions: HaystackTurn[][];
  answer_session_ids: string[];
}

// ---------- Our selected-50 manifest ----------

/** Stored at `bench/longmemeval/selected-questions.json`. Generated by
 *  `select-questions.ts` against a downloaded dataset; reproducible
 *  via the deterministic-by-id rule in spike doc §4.2. */
export interface SelectedManifest {
  /** Filename of the dataset the selection was made against. */
  source_dataset: string;
  /** ISO timestamp the selection was generated. */
  generated_at: string;
  /** Sha256 of the dataset file at the time of selection (paranoia
   *  against silent upstream changes). */
  source_sha256: string;
  /** Per-type counts; must match `expected-distribution.json`. */
  distribution: Partial<Record<LongMemEvalType, number>>;
  /** The 50 chosen question_ids in stable order. */
  question_ids: string[];
}

// ---------- Scoring outputs ----------

/** One row per question after extraction + scoring. */
export interface QuestionScore {
  question_id: string;
  question_type: LongMemEvalType;
  /** Number of session-turns flattened into the conversation. */
  session_turn_count: number;
  /** Memories the extractor produced. */
  extracted_count: number;
  /** Key tokens parsed from the upstream `answer` field. */
  answer_key_tokens: string[];
  /** Tokens that appeared in the joined extracted-memory text. */
  matched_tokens: string[];
  /** Tokens that didn't appear. */
  missed_tokens: string[];
  /** Headline rubric (spike §4.4): 1 if every key token matched, else 0. */
  full_evidence: boolean;
  /** Partial-credit (≥50% tokens matched, but not all). */
  partial_evidence: boolean;
  /** ms spent on the extraction call. */
  latency_ms: number;
  /** Set when extraction itself failed; excluded from headline. */
  error?: string;
}

/** Top-level run output. Markdown report and JSON dump come from the
 *  same struct so they can't drift. */
export interface LongMemEvalScorecard {
  ran_at: string;
  tool_version: string;
  model: string;
  dataset_path: string;
  /** Always 50 (spike §4.2). Asserted at run start. */
  question_count: number;
  /** Number of fully-evidenced questions (the headline number). */
  full_evidence_count: number;
  /** Partial-evidence count (reported separately, NOT in headline). */
  partial_evidence_count: number;
  /** Errored extractions (excluded from headline). */
  error_count: number;
  /** Per-type breakdown. */
  by_type: Array<{
    type: LongMemEvalType;
    n: number;
    full: number;
    partial: number;
    rate: number;
  }>;
  /** Per-question detail. */
  by_question: QuestionScore[];
  total_seconds: number;
}

// ---------- Re-export the memory type so the runner doesn't import
//           it from src/types directly. ----------
export type { MemoryType };
