import { writeFile, mkdir, readFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { CliOptions, ExtractedMemory } from "../types.js";
import { readAllMemories } from "../store/memory-store.js";
import { loadConfig } from "../config.js";
import { resolveAuthor } from "../utils/author.js";
import { printBanner, printError } from "../output/terminal.js";
import {
  AGENTS_MD_DEFAULT_PATH,
  writeAgentsMd,
  type WriteAgentsMdResult,
} from "../rules/agents-md-writer.js";
import {
  SKILLS_DEFAULT_DIR,
  writeSkills,
  type WriteSkillsResult,
} from "../rules/skills-writer.js";

const CURSOR_RULES_DEFAULT = ".cursor/rules/ai-memory-conventions.mdc";

type Target = "cursor-rules" | "agents-md" | "skills" | "both";

interface TargetResult {
  target: "cursor-rules" | "agents-md" | "skills";
  outputPath: string;
  /** "created" | "updated" | "appended" | "already-up-to-date" | "conflict" | "skills-summary" */
  action: string;
  wrote: boolean;
  conventions: number;
  decisions: number;
  /** Per-skill breakdown, only set for target="skills". */
  skills?: WriteSkillsResult["skills"];
  /** Skipped skills (empty source type), only set for target="skills". */
  skippedSkills?: WriteSkillsResult["skipped"];
  reason?: string;
}

function memoryToRule(m: ExtractedMemory): string {
  const lines: string[] = [];
  lines.push(`## ${m.title}`);
  lines.push("");
  lines.push(m.content);
  if (m.reasoning) lines.push("", `Why: ${m.reasoning}`);
  if (m.alternatives) lines.push("", `Rejected alternatives: ${m.alternatives}`);
  return lines.join("\n");
}

function buildCursorRulesFile(
  memories: ExtractedMemory[],
  language: "zh" | "en"
): string {
  const isZh = language === "zh";
  const lines: string[] = [];

  lines.push("---");
  lines.push('description: "Auto-generated from ai-memory extracted conventions and decisions"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");

  const header = isZh
    ? "# 项目约定与决策（由 ai-memory 自动生成）"
    : "# Project Conventions & Decisions (auto-generated by ai-memory)";
  lines.push(header);
  lines.push("");

  const note = isZh
    ? "> 以下规则从 AI 对话历史中提取，请严格遵守，无需重新讨论。"
    : "> These rules were extracted from AI conversation history. Follow them without re-discussion.";
  lines.push(note);
  lines.push("");

  const conventions = memories.filter((m) => m.type === "convention");
  const decisions = memories.filter((m) => m.type === "decision");

  if (conventions.length > 0) {
    lines.push(isZh ? "## 代码约定" : "## Code Conventions");
    lines.push("");
    for (const m of conventions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  if (decisions.length > 0) {
    lines.push(isZh ? "## 技术决策" : "## Technical Decisions");
    lines.push("");
    for (const m of decisions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  return lines.join("\n");
}

async function safeReadFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return null;
  }
}

async function runCursorRulesTarget(
  memories: ExtractedMemory[],
  language: "zh" | "en",
  outputPath: string
): Promise<TargetResult> {
  const conventions = memories.filter((m) => m.type === "convention").length;
  const decisions = memories.filter((m) => m.type === "decision").length;
  const next = buildCursorRulesFile(memories, language);

  const existing = await safeReadFile(outputPath);
  if (existing !== null && existing === next) {
    return {
      target: "cursor-rules",
      outputPath,
      action: "already-up-to-date",
      wrote: false,
      conventions,
      decisions,
    };
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, next, "utf-8");
  return {
    target: "cursor-rules",
    outputPath,
    action: existing === null ? "created" : "updated",
    wrote: true,
    conventions,
    decisions,
  };
}

async function runAgentsMdTarget(
  memories: ExtractedMemory[],
  language: "zh" | "en",
  outputPath: string
): Promise<TargetResult> {
  const r: WriteAgentsMdResult = await writeAgentsMd(memories, {
    language,
    outputPath,
  });
  return {
    target: "agents-md",
    outputPath: r.outputPath,
    action: r.action,
    wrote: r.wrote,
    conventions: r.conventions,
    decisions: r.decisions,
    reason: r.reason,
  };
}

async function runSkillsTarget(
  /** Pass allMemories — skills-writer does its own per-type + status filter. */
  allMemories: ExtractedMemory[],
  language: "zh" | "en",
  outputDir: string
): Promise<TargetResult> {
  const r: WriteSkillsResult = await writeSkills(allMemories, {
    language,
    outputDir,
  });

  const wroteAny = r.skills.some((s) => s.wrote);
  // Action collapses to one line for the per-target summary; the per-skill
  // breakdown lives in `skills` for the JSON output and the human formatter.
  const action: string =
    r.skills.length === 0
      ? "skills-empty"
      : wroteAny
        ? r.skills.every((s) => s.action === "created")
          ? "created"
          : "updated"
        : "already-up-to-date";

  return {
    target: "skills",
    outputPath: outputDir,
    action,
    wrote: wroteAny,
    conventions: r.totals.convention,
    decisions: r.totals.decision,
    skills: r.skills,
    skippedSkills: r.skipped,
  };
}

function formatTargetLine(r: TargetResult): string {
  const label =
    r.target === "cursor-rules"
      ? "Cursor Rules"
      : r.target === "agents-md"
        ? "AGENTS.md"
        : "Anthropic Skills";

  if (r.target === "skills") {
    return formatSkillsLines(r);
  }

  switch (r.action) {
    case "created":
      return `[+] ${label} created -> ${r.outputPath}`;
    case "updated":
      return `[+] ${label} updated -> ${r.outputPath}`;
    case "appended":
      return `[+] ${label} appended (existing content preserved) -> ${r.outputPath}`;
    case "already-up-to-date":
      return `[=] ${label} already up to date -> ${r.outputPath}`;
    case "conflict":
      return `[!] ${label} conflict (not written) -> ${r.outputPath}\n    ${r.reason ?? ""}`;
    default:
      return `[?] ${label} ${r.action} -> ${r.outputPath}`;
  }
}

function formatSkillsLines(r: TargetResult): string {
  // Skills get a multi-line summary because we may have written multiple
  // skill directories and skipped others (empty source type).
  const lines: string[] = [];

  if (r.action === "skills-empty") {
    lines.push(
      `[!] Anthropic Skills: nothing to write -> ${r.outputPath}\n` +
        `    No conventions / decisions / architecture memories found. ` +
        `Run \`ai-memory extract\` first.`
    );
    return lines.join("\n");
  }

  const writtenSkills = r.skills?.filter((s) => s.wrote) ?? [];
  const upToDate = r.skills?.filter((s) => !s.wrote) ?? [];

  if (writtenSkills.length > 0) {
    lines.push(`[+] Anthropic Skills written -> ${r.outputPath}`);
    for (const s of writtenSkills) {
      lines.push(`    ${s.action === "created" ? "+ " : "~ "}${s.name} (${s.memories} ${pluraliseMemory(s.memories)})`);
    }
  } else if (upToDate.length > 0) {
    lines.push(`[=] Anthropic Skills already up to date -> ${r.outputPath}`);
  }

  if (r.skippedSkills && r.skippedSkills.length > 0) {
    const names = r.skippedSkills.map((s) => s.name).join(", ");
    lines.push(`    (skipped, no source memories: ${names})`);
  }

  return lines.join("\n");
}

function pluraliseMemory(n: number): string {
  return n === 1 ? "memory" : "memories";
}

export async function runRules(opts: CliOptions): Promise<number> {
  if (!opts.json) printBanner();

  const config = await loadConfig();
  const outputDir = config.output.dir;
  const language = config.output.language;
  const author = opts.allAuthors ? undefined : await resolveAuthor(config, opts.author);

  const allMemories = await readAllMemories(outputDir, author);

  // The rules pipeline has two memory subsets:
  //   - rulesMemories: convention + active-decision (used by cursor-rules
  //     and agents-md, unchanged from v2.4 behaviour).
  //   - allMemories:   passed wholesale to the skills writer, which
  //     filters internally per its catalogue (also picks up architecture).
  const rulesMemories = allMemories.filter(
    (m) =>
      (m.type === "convention" || m.type === "decision") &&
      m.status !== "resolved"
  );

  const target: Target = opts.target ?? "cursor-rules";

  // Early-exit guards depend on which targets actually run. `skills`
  // accepts architecture-only stores; the other targets do not.
  const targetUsesRulesMemories =
    target === "cursor-rules" || target === "agents-md" || target === "both";
  const targetUsesAllMemories = target === "skills";

  if (targetUsesRulesMemories && rulesMemories.length === 0) {
    printError('No conventions or decisions found. Run "ai-memory extract" first.');
    return 1;
  }
  if (targetUsesAllMemories && allMemories.length === 0) {
    printError('No memories found. Run "ai-memory extract" first.');
    return 1;
  }

  // Custom --output only applies to single-target runs; --target both
  // uses defaults for both files (the user can re-run twice if they want
  // bespoke paths for both).
  const customOutput = target !== "both" ? opts.output : undefined;
  if (target === "both" && opts.output && !opts.json) {
    process.stderr.write(
      `[warn] --output is ignored when --target=both. Using default paths\n` +
        `       (.cursor/rules/ai-memory-conventions.mdc and AGENTS.md). ` +
        `Run the command twice with --target cursor-rules and --target agents-md\n` +
        `       if you need a custom path for one of them.\n`
    );
  }

  const results: TargetResult[] = [];

  if (target === "cursor-rules" || target === "both") {
    const path =
      (target === "cursor-rules" && customOutput) || CURSOR_RULES_DEFAULT;
    results.push(await runCursorRulesTarget(rulesMemories, language, path));
  }

  if (target === "agents-md" || target === "both") {
    const path =
      (target === "agents-md" && customOutput) || AGENTS_MD_DEFAULT_PATH;
    results.push(await runAgentsMdTarget(rulesMemories, language, path));
  }

  if (target === "skills") {
    // For skills, --output is interpreted as the parent directory under
    // which `<skill-name>/SKILL.md` files are written. Default is
    // `.claude/skills`.
    const dir = customOutput || SKILLS_DEFAULT_DIR;
    results.push(await runSkillsTarget(allMemories, language, dir));
  }

  const conventions = rulesMemories.filter((m) => m.type === "convention").length;
  const decisions = rulesMemories.filter((m) => m.type === "decision").length;
  // Architecture is only relevant when the skills target ran (cursor-rules
  // and agents-md both ignore architecture by design — they target the
  // "always-on rules layer", architecture facts are too long-form). When
  // skills wasn't requested we keep the field at 0 rather than omitting it,
  // so consumers of `--json` get a stable schema.
  const architecture = results.some((r) => r.target === "skills")
    ? allMemories.filter((m) => m.type === "architecture").length
    : 0;

  if (opts.json) {
    console.log(
      JSON.stringify({
        rules: rulesMemories.length,
        conventions,
        decisions,
        architecture,
        outputs: results.map((r) => ({
          target: r.target,
          path: r.outputPath,
          action: r.action,
          wrote: r.wrote,
          ...(r.reason ? { reason: r.reason } : {}),
          ...(r.skills
            ? {
                skills: r.skills.map((s) => ({
                  name: s.name,
                  path: s.path,
                  action: s.action,
                  wrote: s.wrote,
                  memories: s.memories,
                })),
              }
            : {}),
          ...(r.skippedSkills && r.skippedSkills.length > 0
            ? {
                skippedSkills: r.skippedSkills.map((s) => ({
                  name: s.name,
                  memoryType: s.memoryType,
                })),
              }
            : {}),
        })),
      })
    );
    // Exit non-zero if any target hit a conflict — useful for CI.
    return results.some((r) => r.action === "conflict") ? 1 : 0;
  }

  console.log("");
  for (const r of results) {
    console.log(formatTargetLine(r));
  }
  console.log(
    `   ${conventions} conventions + ${decisions} decisions`
  );

  if (results.some((r) => r.target === "cursor-rules" && r.wrote)) {
    console.log(`\n   Cursor will automatically apply these rules to AI responses.`);
  }
  if (results.some((r) => r.target === "agents-md" && r.wrote)) {
    console.log(
      `\n   AGENTS.md is read by Codex / Cursor / Windsurf / Copilot / Amp at session start.`
    );
  }
  if (results.some((r) => r.target === "skills" && r.wrote)) {
    console.log(
      `\n   Claude Code will auto-load these skills when their description matches your request.`
    );
  }
  if (results.some((r) => r.action === "conflict")) {
    return 1;
  }

  return 0;
}
