import { writeFile, mkdir, readFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { CliOptions, ExtractedMemory } from "../types.js";
import { readAllMemories } from "../store/memory-store.js";
import { loadConfig } from "../config.js";
import { resolveAuthor } from "../utils/author.js";
import { printBanner, printError } from "../output/terminal.js";
import {
  AGENTS_MD_DEFAULT_PATH,
  writeAgentsMd,
  type WriteAgentsMdResult,
} from "../rules/agents-md-writer.js";

const CURSOR_RULES_DEFAULT = ".cursor/rules/ai-memory-conventions.mdc";

type Target = "cursor-rules" | "agents-md" | "both";

interface TargetResult {
  target: "cursor-rules" | "agents-md";
  outputPath: string;
  /** "created" | "updated" | "appended" | "already-up-to-date" | "conflict" */
  action: string;
  wrote: boolean;
  conventions: number;
  decisions: number;
  reason?: string;
}

function memoryToRule(m: ExtractedMemory): string {
  const lines: string[] = [];
  lines.push(`## ${m.title}`);
  lines.push("");
  lines.push(m.content);
  if (m.reasoning) lines.push("", `Why: ${m.reasoning}`);
  if (m.alternatives) lines.push("", `Rejected alternatives: ${m.alternatives}`);
  return lines.join("\n");
}

function buildCursorRulesFile(
  memories: ExtractedMemory[],
  language: "zh" | "en"
): string {
  const isZh = language === "zh";
  const lines: string[] = [];

  lines.push("---");
  lines.push('description: "Auto-generated from ai-memory extracted conventions and decisions"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");

  const header = isZh
    ? "# 项目约定与决策（由 ai-memory 自动生成）"
    : "# Project Conventions & Decisions (auto-generated by ai-memory)";
  lines.push(header);
  lines.push("");

  const note = isZh
    ? "> 以下规则从 AI 对话历史中提取，请严格遵守，无需重新讨论。"
    : "> These rules were extracted from AI conversation history. Follow them without re-discussion.";
  lines.push(note);
  lines.push("");

  const conventions = memories.filter((m) => m.type === "convention");
  const decisions = memories.filter((m) => m.type === "decision");

  if (conventions.length > 0) {
    lines.push(isZh ? "## 代码约定" : "## Code Conventions");
    lines.push("");
    for (const m of conventions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  if (decisions.length > 0) {
    lines.push(isZh ? "## 技术决策" : "## Technical Decisions");
    lines.push("");
    for (const m of decisions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  return lines.join("\n");
}

async function safeReadFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return null;
  }
}

async function runCursorRulesTarget(
  memories: ExtractedMemory[],
  language: "zh" | "en",
  outputPath: string
): Promise<TargetResult> {
  const conventions = memories.filter((m) => m.type === "convention").length;
  const decisions = memories.filter((m) => m.type === "decision").length;
  const next = buildCursorRulesFile(memories, language);

  const existing = await safeReadFile(outputPath);
  if (existing !== null && existing === next) {
    return {
      target: "cursor-rules",
      outputPath,
      action: "already-up-to-date",
      wrote: false,
      conventions,
      decisions,
    };
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, next, "utf-8");
  return {
    target: "cursor-rules",
    outputPath,
    action: existing === null ? "created" : "updated",
    wrote: true,
    conventions,
    decisions,
  };
}

async function runAgentsMdTarget(
  memories: ExtractedMemory[],
  language: "zh" | "en",
  outputPath: string
): Promise<TargetResult> {
  const r: WriteAgentsMdResult = await writeAgentsMd(memories, {
    language,
    outputPath,
  });
  return {
    target: "agents-md",
    outputPath: r.outputPath,
    action: r.action,
    wrote: r.wrote,
    conventions: r.conventions,
    decisions: r.decisions,
    reason: r.reason,
  };
}

function formatTargetLine(r: TargetResult): string {
  const label = r.target === "cursor-rules" ? "Cursor Rules" : "AGENTS.md";
  switch (r.action) {
    case "created":
      return `[+] ${label} created -> ${r.outputPath}`;
    case "updated":
      return `[+] ${label} updated -> ${r.outputPath}`;
    case "appended":
      return `[+] ${label} appended (existing content preserved) -> ${r.outputPath}`;
    case "already-up-to-date":
      return `[=] ${label} already up to date -> ${r.outputPath}`;
    case "conflict":
      return `[!] ${label} conflict (not written) -> ${r.outputPath}\n    ${r.reason ?? ""}`;
    default:
      return `[?] ${label} ${r.action} -> ${r.outputPath}`;
  }
}

export async function runRules(opts: CliOptions): Promise<number> {
  if (!opts.json) printBanner();

  const config = await loadConfig();
  const outputDir = config.output.dir;
  const language = config.output.language;
  const author = opts.allAuthors ? undefined : await resolveAuthor(config, opts.author);

  const allMemories = await readAllMemories(outputDir, author);
  const memories = allMemories.filter(
    (m) =>
      (m.type === "convention" || m.type === "decision") &&
      m.status !== "resolved"
  );

  if (memories.length === 0) {
    printError('No conventions or decisions found. Run "ai-memory extract" first.');
    return 1;
  }

  const target: Target = opts.target ?? "cursor-rules";

  // Custom --output only applies to single-target runs; --target both
  // uses defaults for both files (the user can re-run twice if they want
  // bespoke paths for both).
  const customOutput = target !== "both" ? opts.output : undefined;
  if (target === "both" && opts.output && !opts.json) {
    process.stderr.write(
      `[warn] --output is ignored when --target=both. Using default paths\n` +
        `       (.cursor/rules/ai-memory-conventions.mdc and AGENTS.md). ` +
        `Run the command twice with --target cursor-rules and --target agents-md\n` +
        `       if you need a custom path for one of them.\n`
    );
  }

  const results: TargetResult[] = [];

  if (target === "cursor-rules" || target === "both") {
    const path =
      (target === "cursor-rules" && customOutput) || CURSOR_RULES_DEFAULT;
    results.push(await runCursorRulesTarget(memories, language, path));
  }

  if (target === "agents-md" || target === "both") {
    const path =
      (target === "agents-md" && customOutput) || AGENTS_MD_DEFAULT_PATH;
    results.push(await runAgentsMdTarget(memories, language, path));
  }

  const conventions = memories.filter((m) => m.type === "convention").length;
  const decisions = memories.filter((m) => m.type === "decision").length;

  if (opts.json) {
    console.log(
      JSON.stringify({
        rules: memories.length,
        conventions,
        decisions,
        outputs: results.map((r) => ({
          target: r.target,
          path: r.outputPath,
          action: r.action,
          wrote: r.wrote,
          ...(r.reason ? { reason: r.reason } : {}),
        })),
      })
    );
    // Exit non-zero if any target hit a conflict — useful for CI.
    return results.some((r) => r.action === "conflict") ? 1 : 0;
  }

  console.log("");
  for (const r of results) {
    console.log(formatTargetLine(r));
  }
  console.log(
    `   ${conventions} conventions + ${decisions} decisions`
  );

  if (results.some((r) => r.target === "cursor-rules" && r.wrote)) {
    console.log(`\n   Cursor will automatically apply these rules to AI responses.`);
  }
  if (results.some((r) => r.target === "agents-md" && r.wrote)) {
    console.log(
      `\n   AGENTS.md is read by Codex / Cursor / Windsurf / Copilot / Amp at session start.`
    );
  }
  if (results.some((r) => r.action === "conflict")) {
    return 1;
  }

  return 0;
}
