import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import type { CliOptions, ExtractedMemory } from "../types.js";
import { readAllMemories } from "../store/memory-store.js";
import { loadConfig } from "../config.js";
import { resolveAuthor } from "../utils/author.js";
import { printBanner, printError } from "../output/terminal.js";

const DEFAULT_OUTPUT = ".cursor/rules/ai-memory-conventions.mdc";

function memoryToRule(m: ExtractedMemory): string {
  const lines: string[] = [];
  lines.push(`## ${m.title}`);
  lines.push("");
  lines.push(m.content);
  if (m.reasoning) lines.push("", `Why: ${m.reasoning}`);
  if (m.alternatives) lines.push("", `Rejected alternatives: ${m.alternatives}`);
  return lines.join("\n");
}

function buildRulesFile(memories: ExtractedMemory[], language: "zh" | "en"): string {
  const isZh = language === "zh";
  const lines: string[] = [];

  lines.push("---");
  lines.push('description: "Auto-generated from ai-memory extracted conventions and decisions"');
  lines.push("alwaysApply: true");
  lines.push("---");
  lines.push("");

  const header = isZh
    ? "# 项目约定与决策（由 ai-memory 自动生成）"
    : "# Project Conventions & Decisions (auto-generated by ai-memory)";
  lines.push(header);
  lines.push("");

  const note = isZh
    ? "> 以下规则从 AI 对话历史中提取，请严格遵守，无需重新讨论。"
    : "> These rules were extracted from AI conversation history. Follow them without re-discussion.";
  lines.push(note);
  lines.push("");

  const conventions = memories.filter((m) => m.type === "convention");
  const decisions = memories.filter((m) => m.type === "decision");

  if (conventions.length > 0) {
    lines.push(isZh ? "## 代码约定" : "## Code Conventions");
    lines.push("");
    for (const m of conventions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  if (decisions.length > 0) {
    lines.push(isZh ? "## 技术决策" : "## Technical Decisions");
    lines.push("");
    for (const m of decisions) {
      lines.push(memoryToRule(m));
      lines.push("");
    }
  }

  return lines.join("\n");
}

export async function runRules(opts: CliOptions): Promise<number> {
  if (!opts.json) printBanner();

  const config = await loadConfig();
  const outputDir = config.output.dir;
  const language = config.output.language;
  const author = opts.allAuthors ? undefined : await resolveAuthor(config, opts.author);

  const allMemories = await readAllMemories(outputDir, author);
  const memories = allMemories.filter(
    (m) =>
      (m.type === "convention" || m.type === "decision") &&
      m.status !== "resolved"
  );

  if (memories.length === 0) {
    printError('No conventions or decisions found. Run "ai-memory extract" first.');
    return 1;
  }

  const rulesContent = buildRulesFile(memories, language);
  const outputPath = opts.output || DEFAULT_OUTPUT;

  if (opts.json) {
    console.log(JSON.stringify({ rules: memories.length, output: outputPath }));
    return 0;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, rulesContent, "utf-8");

  console.log(`\n[+] Generated Cursor Rules -> ${outputPath}`);
  console.log(`   ${memories.filter((m) => m.type === "convention").length} conventions + ${memories.filter((m) => m.type === "decision").length} decisions`);
  console.log(`\n   Cursor will automatically apply these rules to AI responses.`);

  return 0;
}
